### ISSUE TITLE
error curl

### ISSUE THREAD

**Issue by chassain** [AlexanderSalter/MMM-Instagram2020#1]
Hello,

Nice work..just a problem with curl at this step

pi@raspberrypi:~ $ curl -X POST \ https://api.instagram.com/oauth/access_token \ -F client_id=108...... \ -F client_secret=491f... \ -F grant_type=authorization_code \ -F redirect_uri=https://socialsizzle.herokuapp.com/auth/ \ -F code=AQChY....
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: client_id=10.....
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: client_secret=491f....
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: grant_type=authorization_code
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: redirect_uri=https
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: code=AQChYc7.........

**Comment by AlexanderSalter** [comment]
Hello,

Not to worry, it looks like you have made it all the way to Step 5 in the Facebook developers guide.
This means you have all you need.
You only need to follow up to and including Step 3 to ensure to make sure you have got the **app-id**, **redirect-uri** and **referral_code** for your configuration.
If you follow the Authorisation guide in the readme with those variables it will all work nicely.
