### ISSUE TITLE
Autorisation problems

### ISSUE THREAD

**Issue by vintage8902** [AlexanderSalter/MMM-Instagram2020#12]
Hey,
I managed to get alle the way to Authorizing. But when I hit «Authorize» the screen just goes black. I can see no adress line or anything.
I’m doing the process through vnc onto my raspberry pi.

Anyone with a similar problem or a solution?
Maybe if anyone has a copy of the «Here» url, that I could just put in my information in.

**Comment by AlexanderSalter** [comment]
Hi Vintage,

When you click the "Authorize" button in step 6 you will get a blank page, the important part is the URL returned, you need the end of the url "**?code= <<<auth_code>>> #_**" as per step 7.

The key will be unique fro user to user so you will need to obtain your own auth key.

Hope it helps!
