### ISSUE TITLE
No adress bar by auth.

### ISSUE THREAD

**Issue by Jasa1983** [AlexanderSalter/MMM-Instagram2020#16]
Hi, have started the auth. process by clicking at my MM as in the description. New window is poping up where i am asked for access. But there is no adress bar where i can copy the auth code. Have someone an idea what i should do?
![1](https://user-images.githubusercontent.com/80083814/163836100-2fa39469-10b2-4da2-a481-9f449f478f16.jpg)

**Comment by ruffneck2** [comment]
Can I ask you what entries you have made for the MM website? I keep failing, especially when entering the "Valid OAuth Redirect URIs", "Deauthorize callback URL" and "Data Deletion Request URL".
May I ask you about your settings to display these on the MM? Or maybe you can give me some more tips, as I've been stuck on this for days.

**Comment by AlexanderSalter** [comment]
> Hi, have started the auth. process by clicking at my MM as in the description. New window is poping up where i am asked for access. But there is no adress bar where i can copy the auth code. Have someone an idea what i should do? ![1](https://user-images.githubusercontent.com/80083814/163836100-2fa39469-10b2-4da2-a481-9f449f478f16.jpg)

So it looks like the default browser on the Pi has changed = no access to address.
I did some testing last night and was able to get things going using two methods:
1) Enable remote access to the MM interface and competing the auth there > opens your default browser
2) Use the "User Token Generator" under FacebookDev > Instagram Basic Display > Basic Display to generate a token then update MagigMirror/modules/MMM-Instagram/accesstoken.cfg with the token.
In Case 2 the config should ommit auth_code.

**Comment by AlexanderSalter** [comment]
> Can I ask you what entries you have made for the MM website? I keep failing, especially when entering the "Valid OAuth Redirect URIs", "Deauthorize callback URL" and "Data Deletion Request URL". May I ask you about your settings to display these on the MM? Or maybe you can give me some more tips, as I've been stuck on this for days.

 {
                        module: 'MMM-Instagram2020',
                        position: 'bottom_right',
                        header: 'MMM-Instagram2020',
                        config: {
                                client_id: '<<Instagram App ID>>', // Facebook Instagram App ID
                                client_secret: '<<Instagram App Secret>>', // Facebook Instagram App Secret
                                redirect_uri: 'https://MAGICMIRRORIP:8080/auth/', // Facebook Instagram App redirect_uri
                                auth_code: '<<WhateverReturnedByAuth>>',
                                animationSpeed: 1000,
                                updateInterval: 30000,
                        }
                },

The redirect_uri is just a dummy URL at the moment and is only used to gain access to a URL that includes the auth_code,
I can see room for improvement by making an auto-handler url that takes the auth_code and process it to an access_token automatically.

I suggest using the method above by directly providing the accesstoken to accesstoken.cfg.

**Comment by AlexanderSalter** [comment]
@ruffneck2 @Jasa1983 i jsut updated the Module that automates the process, it does require Magic Mirror to be in https/ssl mode. I have also updated the readme accordingly.
Let me know if it works for you.

Commit Ref: https://github.com/AlexanderSalter/MMM-Instagram2020/commit/6f8254beaa2c5f259abec9b82c49e15b308449db

**Comment by AlexanderSalter** [comment]
Closed as resolved

**Comment by Jasa1983** [comment]
Thx a lot, work Perfect.

**Comment by ruffneck2** [comment]
It works for me too, thank you!

**Comment by AlexanderSalter** [comment]
@Jasa1983  & @ruffneck2 thank you for confirming it works 👍
