### ISSUE TITLE
missed images

### ISSUE THREAD

**Issue by chassain** [AlexanderSalter/MMM-Instagram2020#2]
Hello Alexander,

again me :)...it's ok now to display images but i haven't all images of my instagram's profil. Do you see this ?
Thanks again for you great work..

**Comment by AlexanderSalter** [comment]
Chassain,

Glad you can now see the images.

I just quickly checked;
The "first image" of the first post/album is displayed
Then the next post/album "first image" is shown.
The the next post/album "first image" is shown... and so on.

The app will show the first "n" albums and will rotate the display the first image from each of the posts/albums.

What were you hoping to see:
1) All images from albums?
This should be doable, with changes, but will need to adjust the code to read the contents of an album.
2) All images on the profile?
This should be doable, with changes, but will need to adjust the code to read the next set of images as the initial number of returned images is limited by the API.
3) Combination 1 and 2? 
This should be doable but will need both of the above.

**Comment by chassain** [comment]
it's solution 2. All images..i haven't albums, only images..
i understand API limites number of images
Thanks

**Comment by AlexanderSalter** [comment]
Chassain,

Understood, I have marked this as a new feature as the code will need to be modified to include additional calls to get more images.
Thanks for the clarification.

**Comment by AlexanderSalter** [comment]
@chassain I jsut fixed an issue that caused the MMM-Instagram2020 module to skip image 1 > 3 > 5 e.t.c. it should now be behaving.

**Comment by AlexanderSalter** [comment]
Created two new features:
https://github.com/AlexanderSalter/MMM-Instagram2020/issues/20
https://github.com/AlexanderSalter/MMM-Instagram2020/issues/21
