### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by AndrewSav** [AlexanderSalter/MMM-Instagram2020#3]
First of all, thank you for sharing you work, it is very much appreciated.

I gave this module a go today, and here are possible improvements:

- In the readme, the configuration example has unmatching brackets
- It would be nice if the guide gave a recommendation with regards to the 3 call-back urls the facebook/instagram require. It's true, that those mostly do not matter, yet many readers would not know that. An advice to use `https://localhost/` for all of them would help.
- During authorization process, we need to click a link in MagicMirror, but the mouse pointer may be hidden. It's trivially resolved by right-clicking anywhere in the browser window, but it might not come to one's mind readily, so a note to this effect would be welcome
- There is unclarity in the note at the end of authorization process. It says that `a key stored in accesstoken.cfg` but then goes on to refer to `the access token` that is never mentioned before. It's better to either refer to that as to `the key` in the second mention or as `access token` in the first, otherwise it is not clear that we are talking about the same thing. It is also unclear why, if "There is a mechanism in place to renew the key every time MagicMirror2 is restarted", we might need to "just repeat the authorisation process" if "the access token gets to old". This might benefit from further elaboration.
- It seems that the module completely ignores existence of other post types than photo (such as a video, a gallery, etc) which makes it display a broken square when the link to a photo not found. While there is a TODO item that acknowledges that video support is desirable, separately to that, the module should detect the situation when it cannot render the content and not show the broken image in this case. Skipping over and logging a warning may be a reasonable alternative to the current behaviour.
- If an item lacks a comment, `undefined` is displayed. This has no value for anyone watching the frame, so that needs to be hidden
- The log of the module is rather spammy. Good for debugging but may be possible to tone down for "production" use, with an option to display more if required?

Thank you in advance!

**Comment by AlexanderSalter** [comment]
Andrew,

Your feedback is very much appreciated.

I have marked this as "enhancement" and will work through the items when i get some time or move them to separate items if i cannot resolve.

Feel free to dive in and make updates =)

Thanks again for raising the above.

**Comment by AlexanderSalter** [comment]
Moved each item into a unique item for better tracking.
Closed this to avoid open duplicates.
